import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import prisma from '../lib/prisma';
import PostCard from '../components/PostCard'


export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h1>
            Hello World. This is the main place, yo.
          </h1>
          <div className="grid md:grid-cols-3 sm:grid-cols-2 grid-cols-1 justify-items-center  gap-4">
          {posts.map((post:any) => (
            <PostCard post={post} key ={post.id}/>
          ))}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const posts = await prisma.post.findMany();
  return {
    props: { posts },
  };
}
