import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { SignUp } from "@clerk/nextjs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h1>
            Hello World. This is the main place, yo.
          </h1>
          <SignUp path="/sign-up" routing="path" signInUrl="/sign-in" />
      </main>
    </>
  )
}
